#ifndef _CONFIG_H_
#define _CONFIG_H_

/* LCD */
#define LCD_PIX_WIDTH		640
#define LCD_PIX_HEIGH		480

/* CAPTURE */
#define CAPTURE_PIX_WIDTH		LCD_PIX_WIDTH
#define CAPTURE_PIX_HEIGH		LCD_PIX_HEIGH
#define ONE_CAP_FRAME_SIZE		(CAPTURE_PIX_WIDTH*CAPTURE_PIX_HEIGH)

#define FACE_RECO_THRES 	85.5

#endif	// _CONFIG_H_
